// (C) Copyright 2014-2017 The Khronos Group Inc. All Rights Reserved.
// Khronos Group Safety Critical API Development SCAP
// document
// 
// Text format: asciidoc 8.6.9
// Editor:      Asciidoc Book Editor
//
// Description: Guidelines 3.2.5 Guidelines Bugzilla #16024

:Author: Illya Rudkin (spec editor)
:Author Initials: IOR
:Revision: 0.02

// Hyperlink anchor, the ID matches those in 
// 3_1_GuidelinesList.adoc 
[[b16024]]

==== 3.2.5 Explicit Timeout Values

Similar to being able to accurately control memory usage on an embedded system, in a SC system the execution time must be accurately controlled. A key requirement of system safety certification is to guarantee that a program has the required amount of execution time for its worst case execution behavior. This is referred to as the systems Worst Case Execution Time. To this extent many safety critical operating system provide time partitioning and guarantees about how long any single operating system call may take. If an application exceeds its time budget the application can be forced to shut down.

SC API implementations must also provide similar guarantees about how long a single call will take based on the current state. However there exist some APIs calls which cause the system to wait for an external event or state change to occur. These APIs should provide the application the ability to set a particular maximum time to wait for the occurrence of the event or state change. This allows the application to minimize Worst Case Execution Times by being programmed to handle asynchronous execution of long waits, instead of stalling the program until the event or state change occur.

There exist many ways to set such a maximum wait time. The POSIX family of functions +*_timedwait+ uses a parameter to the actual function call to accomplish this. However adding timeout parameters would change the function signature of well established functions may not be desired. As an alternative to adding a specific timeout parameter to the function call the timeout value could be set using a standard state setting function. An example in OpenGL may be to use +glSetInteger+. In this case the timeout value is set before the function is called and stored for when the function is called. In Vulkan the timeout value may be passed to the function via an extension structure via the +pNext+ parameter. These are just some examples of how this might be solved, but it is left up to the API designers to determine the best way to accomplish this for the particular API.