// (C) Copyright 2014-2017 The Khronos Group Inc. All Rights Reserved.
// Khronos Group Safety Critical API Development SCAP
// document
// 
// Text format: asciidoc 8.6.9
// Editor:      Asciidoc Book Editor
//
// Description: Guidelines 3.2.16 Guidelines Git #16

:Author: Illya Rudkin (spec editor)
:Author Initials: IOR
:Revision: 0.03

// Hyperlink anchor, the ID matches those in 
// 3_1_GuidelinesList.adoc 
[[gh16]]

ifdef::basebackend-docbook[]
=== Non recoverable error conditions and reporting status
endif::[]
ifdef::basebackend-html[]
=== {chapter-id}.{chapter-sub-id}.{counter:section-id}. Non recoverable error conditions and reporting status
ndif::[]

Also see:

- No underfined behavior

A system should facilitate the communication of all its operational states to its client or monitoring system efficiently and effectively to aid its development, testing regime and deployment. A system could communicate state using:  

- The interface’s or API functions’ parameters  
- Drive signals on connected hardware  
- Write diagnostics to shared memory

The critical safety level of the system will likely dictate the partitioning design of the system with other components which in turn will influence how a SC system communicates its state.

It is important that all states and error conditions are described discretely and not grouped into a general state or error condition. The system should be expected to provide information about itself at anytime in a deterministic and timely manner in what ever operational mode it is currently in. For example:  

- Normal running behavior  
- A safety mode, reduced functionality ‘limp home’ mode  
- Indeterminate unrecoverable state

For highly critical safety systems a separate Watch Dog component is likely to be deployed to oversee those critical systems and monitor their behavior for abnormal events which then signals higher level systems to take appropriate corrective action.

A safety critical system’s API should be documented including:  

- Normal behavioral states 
- All error states  
- All safety mode limiting behavioral states, how they are entered and whether they are recoverable  
- All non deterministic non recoverable states and how they are entered.

Ideally a safety critical system should not have any non deterministic non recoverable operational states.