// (C) Copyright 2014-2018 The Khronos Group Inc. All Rights Reserved.
// Khronos Group Safety Critical API Development SCAP
// document
//
// Text format: asciidoc 8.6.9
// Editor:      Asciidoc Book Editor
//
// Description: Guidelines 3.2.6 Guidelines Github #3

:Author: Illya Rudkin (spec editor)
:Author Initials: IOR
:Revision: 0.04

// Hyperlink anchor, the ID matches those in
// 3_1_GuidelinesList.adoc
[[gh3]]

ifdef::basebackend-docbook[]
=== MISRA compliance
endif::[]
ifdef::basebackend-html[]
=== {chapter-id}.{chapter-sub-id}.{counter:section-id}. MISRA compliance
endif::[]

MISRA, Motor Industry Software Reliability Association, C and
MISRA pass:[C++] are sets of software development guidelines for the C and pass:[C++] programming languages. Their aims are to facilitate code safety, security, portability and reliability in the context of embedded systems. MISRA has evolved as a widely accepted model for best practices by leading developers in sectors including automotive, aerospace, telecom, medical devices, defence, railway, and others.

Many companies that develop software in the safety domain have this standard or similar quality standards as an integral part of their quality management process to provide assurance during safety assessment by internal or external audits. An integral part can in some cases mean it must be complied with.

MISRA rule parsing is available through various code quality management tools. The MISRA standard document lists the rules or requirements with context and examples. The document can be purchased from MISRA directly. Tools implement the standard and parse source code to produce a report. A MISRA qualification tool would produce a typical report such as that shown below.

[source]
Summary:
[50] MISRA C++ 2008 (MISRA2008)
[11] [2] [23]
[1] The plain char type shall only be used for the storage and use of character values (MISRA2008-5_0_11-3)
[3] An implicit integral conversion shall not change the signedness of the underlying type (MISRA2008-5_0_4_a-3)
[2] A variable which is not modified shall be const qualified (MISRA2008-7_1_1-3)
[2] using-directives shall not be used (MISRA2008-7_3_4-3)
[2] typedefs that indicate size and signedness should be used in place of the basic numerical types (MISRA2008-3_9_2-4) [4] Functions should not call themselves, either directly or indirectly (MISRA2008-7_5_4-4)
The source.cpp file with issues (by line number):
A class, union or enum name (including qualification, if any) shall be a unique identifier (MISRA2008-2_10_4_a-3)
An identifier declared to be an object or type shall be defined in a block that minimizes its visibility (MISRA2008-3_4_1_b-3)
The types used for an object, a function return type, or a function parameter shall be token-for-token identical in all declarations and re- declarations (MISRA2008-3_9_1-3)
dtp Recommended Tasks to Accomplish Today : 50
/Analysis/../llvm/lib/Analysis/AliasAnalysis.cpp
102: A tag name 'Result' is reused

Code quality standards like MISRA 'C' 2012 or CERT coding standards can also be used to support functional safety standards like ISO 26262 in order to provide evidence that the code is operating as expected in all circumstances because of either implementation or random errors.

Unlike code quality standards functional safety standards are aimed at the program binary (as a result of a program being compiled) up to the system architectural behavioural level.

It is recommended that a Khrono SC API follows the MISRA
C or MISRA pass:[C++] guidelines as it is can be assumed that the development of an SC API implementation would also follow MISRA guidelines and by not providing a MISRA compliant SC API could mean the standard is not adopted without further modification.

For more information on MISRA visit the following web links: +
- https://en.wikipedia.org/wiki/MISRA_C +
- https://www.misra.org.uk +
