// (C) Copyright 2014-2018 The Khronos Group Inc. All Rights Reserved.
// Khronos Group Safety Critical API Development SCAP
// document
//
// Text format: asciidoc 8.6.9
// Editor:      Asciidoc Book Editor
//
// Description: Guidelines 3.2.6 Github #8 Bugzilla #16059

:Author: Illya Rudkin (spec editor)
:Author Initials: IOR
:Revision: 0.04

// Hyperlink anchor, the ID matches those in
// 3_1_GuidelinesList.adoc
[[gh8]]

ifdef::basebackend-docbook[]
=== Handling of error conditions
endif::[]
ifdef::basebackend-html[]
=== {chapter-id}.{chapter-sub-id}.{counter:section-id}. Handling of error conditions
endif::[]

Also see:

- Lost context

Collectively an SC API specification should list all the possible error conditions that can occur with a one to one mapping to the matching error description that can be provided. There should not be any unnecessary over generalisation of errors descriptions to cover multiple error conditions where distinctions can be made and returned to the client.

For non-recoverable errors the same guidance applies where possible. It is also advised that for the non-recoverable errors that they are listed separately to normal operational errors to make the distinction clear.

Depending on the SC hazard level, the higher it is, there is likely the need for the client to want to be able to access an error description for those parts of a system that are not recoverable so that it may carry out appropriate planned action.
