// (C) Copyright 2014-2018 The Khronos Group Inc. All Rights Reserved.
// Khronos Group Safety Critical API Development SCAP
// document
//
// Text format: asciidoc 8.6.9
// Editor:      Asciidoc Book Editor
//
// Description: Guidelines 3.2.3 Guidelines Bugzilla #15993

:Author: Illya Rudkin (spec editor)
:Author Initials: IOR
:Revision: 0.04

// Hyperlink anchor, the ID matches those in
// 3_1_GuidelinesList.adoc
[[b15993]]

ifdef::basebackend-docbook[]
=== Conformance testing
endif::[]
ifdef::basebackend-html[]
=== {chapter-id}.{chapter-sub-id}.{counter:section-id}. Conformance testing
endif::[]

It is not the intent for Khronos conformance tests for Safety Critical technologies to used or supplied for certification testing. The intent for the Khronos conformance tests are to test the implementations conformance with the specification to ensure that all implementations share the same contract with the application and thereby avoid industry fragmentation through different behavior for the same function.

Please read the
<<Guideline_2_1_SCAPRiderStatement,guideline statement>>.

Further reading: SCAP Requirements: Fully testable.
