// (C) Copyright 2014-2018 The Khronos Group Inc. All Rights Reserved.
// Khronos Group Safety Critical API Development SCAP
// document
//
// Text format: asciidoc 8.6.9
// Editor:      Asciidoc Book Editor
//
// Description: Guidelines 3.2.5 Guidelines Bugzilla #16024

:Author: Illya Rudkin (spec editor)
:Author Initials: IOR
:Revision: 0.055

// Hyperlink anchor, the ID matches those in
// 3_1_GuidelinesList.adoc
[[b16011]]

ifdef::basebackend-docbook[]
=== Debug functionality
endif::[]
ifdef::basebackend-html[]
=== {chapter-id}.{chapter-sub-id}.{counter:section-id}. Debug functionality
endif::[]

In the safety critical domain it is recognised as good practice and some cases a requirement the code which is not executed at all during its lifetime should be removed. This implies for debug functionality which is not used during final run-time should be moved to an extension so that it does not need to go through the safety certification process for the final product release.

If the debug functionality is used to determine the safety requirements are being met the code used to achieve the debug functionality should still be put through the same safety rigour as the code that remains in the final binary.
